/******************************************************************************
 * Copyright 2022 - NESTWAVE SAS
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
 * USE OR OTHER DEALINGS IN THE SOFTWARE.
 *****************************************************************************/
package com.nestwave.device.coap.resource;

import com.nestwave.device.DeviceApplication;
import com.nestwave.device.config.DeviceConfig;
import com.nestwave.device.service.NavigationService;
import lombok.extern.slf4j.Slf4j;
import org.eclipse.californium.core.CoapClient;
import org.eclipse.californium.core.CoapResponse;
import org.eclipse.californium.core.coap.CoAP;
import org.eclipse.californium.elements.exception.ConnectorException;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import java.io.IOException;
import java.nio.charset.StandardCharsets;

import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(SpringExtension.class)
@SpringBootTest(classes = DeviceApplication.class)
@ContextConfiguration(classes = DeviceConfig.class)
@Slf4j
class CoapNavigationResourceTest {

    @MockBean
    NavigationService navigationService;


    @Test
    public void should_call_navigation_coap_server(){

        CoapClient client = new CoapClient("coap://aidefix.nestwave.com:5683/v0/gpsPosition?gpsPositionTime=1211999063");
        String paylod = "HdTrdQoACAAAAAgFBAAAAAMAY7TjqO1tAAB0+jECEgAEANoFBAAAAAIAqDTU2yhBAABfcq8JCwD7/8UACAAAAAIAsBO6+d5CAABc7YYNGwAAAAYACQAAAAIAOMzfWnNZAACNo/j4CgCb/7MACgAAAAIAKLuN5Xw0AAArsB76AQAPAM8CCgAAAAMAlh9hbtI9AABkprENFgA0AD0CDQAAAAIAKPlD03UfAADI9+8PIADj/+EHDQAAAAIAKEtA2m8QAACXfloLHADd/4oBEAAAAAIA6lRtNHcQAADw5KILDgBLABQCEQAAAAIAwJJ8HjYMAAAD8wIPAAAAAAAAAAAAAM7/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAM7/AAAAAAAAAAAAAAAAcvtiYm9PSEBc5o9AD0UDQABACTiWrF5AAAAAi2xPSEAAAACABEUDQAAAAAAAgFRAAICH5cG9qD8ACKBR1hS6PwAA5XzgVsE/eAQAAO19TZERnhVAiBMAAIwPMgJ0AQAAX1mvCe4AAAD4uoYNJgEAAF15+PiFAQAAI5Ae+rUAAAAoZbENuQAAADir7w/RAAAAw39aC4kAAABk2qILZwAAAJ+OAg9nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAABAAAAAQAAAAAAAAABAAAAAQAAAAEAAAABAAAAAgAAAAAAAAAAAAAAAACnDDYBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUuzL+JtyVEAAAAAAAAAAAIiYW4pXkQNAWcWkI6IQAkDietZUSjGwP2Jo1tJHqQpAwG1Ip0Z7AUAAAAAAAAAAAAAAAACmETcBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA59CUjDz/TkAAAAAAAAAAAN76/BOK7QVABD3vkOK/A0DbGY5wSjGwPwRmBJ4SXvY/ALchbdD05D8AAAAAAAAAAAAAAACGBUMBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0tfxAId7R0AAAAAAAAAAAKobd4vndwpAcxMWUeV7B0B1fvuVSjGwP0XOAHuPbvO/gCRvUhIG+r8AAAAAAAAAAAAAAAAONkwBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAX2uiOJSERkAAAAAAAAAAADrZe93WWAtAHKq5TJt3CECWKZykSjGwP5+ekkZU4gHAQJK3Y9uAA8AAAAAAAAAAAAAAAACrWFABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzYc1Zo0kREAAAAAAAAAAAJdtRjCC6Q1A6pjOGr9qCEBPRk1aSjGwPzapjBMvnAdAwG3IZFd6BkAAAAAAAAAAAAAAAACgdFABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxez90RZaQkAAAAAAAAAAAJRt+J4LKxBAhJnqlhJ0DEBM8r11SjGwP3nt/8sdk/A/ALchSZOv4D8AAAAAAAAAAAAAAAD2NFwBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACRK8JXO5PUAAAAAAAAAAAFY5cAUUdhNAZQQc+dpZEUCjdnuHSjGwP8oYouBN58m/gCRvwltE878AAAAAAAAAAAAAAADAB18BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkJBiotw2PEAAAAAAAAAAAHRspEI4ZxRAt9YKSSCMD0CqCdzWSjGwP+avvKvN+BbAIMkbEqmOGcAAAAAAAAAAAAAAAADmtm4BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVpTle4k4NkAAAAAAAAAAAAAAAAAAABhAtiVfo9QOEUDyCa+BSjGwP8oYouBN58k/gCRvJ8A+8b8AAAAAAAAAAAAAAABR228BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcehUxa2zMEAAAAAAAAAAAAAAAAAAABhANzcEpPTnFEDtOtwnSjGwP4RRkn114xlA4DbkSbKxFUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIgTAAAAAAAAcBsSCzlNKcBgAInOPLxlwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFkv+9KdGVBBrNytvwKsBUGUnm0cPCtSQQAAAAAAAA==";
        CoapResponse response = null;
        try {
            //response = client.post(paylod.getBytes(StandardCharsets.UTF_8),1);
            response = client.post(paylod,1);
        } catch (ConnectorException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }if (response!=null) {
            assertEquals(CoAP.ResponseCode.VALID, response.getCode());
        } else {
            log.error("Request failed");
        }
    }

    @Test
    public void should_return_error_when_call_navigation_coap_server(){

        CoapClient client = new CoapClient("coap://aidefix.nestwave.com:5683/gpsPosition?gpsPositionTime1=1211997625");
        String paylod = "AcQccwoACADL/wcACAAAAAMAiwTyZv9HAABC1I8EGwDs//oACgAAAAIAOAwpX7pLAAAbnqD6EgAgAB4GCQAAAAIAc5N4QtIsAACLbloLCgDg/xAECwAAAAIAOHuDEtU8AACSQRH8CwAZAKUHDQAAAAIAhTeDvf4cAAC1N4sOAQDc/7UBEAAAAAMAAEJplC8TAAA2SXEOIADu/2cDEwAAAAIAYF4CdT4ZAAByb/oMFgAXAFEFEwAAAAIAoVx6zJQEAAAf654QHACd/38FAQABAAIA8HSeQvsJAAAdPjANFABJAGMGAAABAAIAeD4qy3QBAABszm71AAAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAC/Fy3qEZUEFsmpAiBawFQVQ8DVc+K1JBAAAAi2xPSEAAAACABEUDQAAAAAAAgFRA0yGhMDuB67+civcqa2f5v03zNCKcQwTAZAMAAELUjwSjAQAAG565+s8AAACLbkELvwAAAJJBEfz9AAAAtTdyDtMAAAA2SVgOgAAAAHJv+gwNAQAAH+uFEDQAAAAdPjANYgAAAGzOVfUnAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAAAAAAAAgAAAAAAAAAAAAAAAADDOzYBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXXGv41AMVEAPBopbYacDQB/yjbUB+AJAPCLvzZetrj8SYfk0IMP8P9BDe3t9BeQ/AAAAAAAAAAAAAAAAaRRCAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALYT0HnLGExAogeX4UlMB0DzioKo1iMGQPgXiiqYra4/MbjuegHz9r8YXkId9zj4vwAAAAAAAAAAAAAAACrXPgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACzoBdThepJQJHeCnjTnQhAAs8e0XZWB0BmEljYl62uPzG47noB8/Y/6KG95la58D8AAAAAAAAAAAAAAAD/l0cBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7KrjwZqkSEC2dzkyN4gJQMg/cHZA6gZAGWshdpitrj8LVdzmOkoQwIaXkLBazhHAAAAAAAAAAAAAAAAA7JJOAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYtnBI7b0JANrDs0pUbEED6tDS1e0INQGCLb4iXra4/vBnnr4TkEED00F7WbYEOQAAAAAAAAAAAAAAAAKsFXAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABC/iQhcmc7QIZBnS4d9BRA7LgQ8rI6EkBs3MJfl62uP6EjJqUlkhZAemgve4PoEkAAAAAAAAAAAAAAAACHqmgBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJk2Pj+EtNUAAAAAAAAAYQBPS/LlCpBNAc+1sl5etrj9xbiM6oJkNQPTQ3vrxIAhAAAAAAAAAAAAAAAAA+ilqAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN4nsqcJKjNAAAAAAAAAGEBHfC5MProXQCghdoCYra4/XAAAtm+7EcCGl5BeYNkVwAAAAAAAAAAAAAAAAOCYeAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1lYQ4aAAvQAAAAAAAABhAuK7sgZIxE0Bh0Q+vmK2uP63rOnbXPBjAhpeQlOSQG8AAAAAAAAAAAAAAAACgkXMBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/veYJQPKUAAAAAAAAAYQAD0WzXA1RNAUzdefpetrj+DdnhdUUwSQHpoL1C0FRFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPbSX+fW6KsBwicT1CfthwAAAAAA=";
        CoapResponse response = null;
        try {
            response = client.post(paylod.getBytes(StandardCharsets.UTF_8),1);
        } catch (ConnectorException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        if (response!=null) {
            assertEquals(response.getCode(), CoAP.ResponseCode.BAD_REQUEST);
        } else {
            log.error("Request failed");
        }
    }

}